### ISSUE TITLE
Make install fail

### ISSUE THREAD

**Issue by mdatz** [o2sh/provok#1]
Not sure if this has something to do with my Ubuntu install but here is the error message I am getting:

[] ~/Programs/provok <main> ✗ make install
cargo build --release 
   Compiling provok v0.1.0 (/home/goku/Programs/provok)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.0.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.1.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.10.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.11.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.12.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.13.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.14.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.15.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.2.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.3.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.4.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.5.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.6.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.7.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.8.rcgu.o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.9.rcgu.o" "-o" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c" "/home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.2i1tlap3n127qpe8.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/goku/Programs/provok/target/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/goku/Programs/provok/target/release/build/harfbuzz-sys-3f02194fa742d47a/out" "-L" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/goku/Programs/provok/target/release/deps/libserde_json-7b8db0c48a777e68.rlib" "/home/goku/Programs/provok/target/release/deps/libryu-8d3adba72655c18e.rlib" "/home/goku/Programs/provok/target/release/deps/libitoa-20dbd03a09e73985.rlib" "/home/goku/Programs/provok/target/release/deps/libttf_parser-b3675e36308bdb1f.rlib" "/home/goku/Programs/provok/target/release/deps/libeuclid-5b3bd763211c1d37.rlib" "/home/goku/Programs/provok/target/release/deps/libharfbuzz_sys-defac85b8605acf9.rlib" "/home/goku/Programs/provok/target/release/deps/libfreetype-700f43e775185dad.rlib" "/home/goku/Programs/provok/target/release/deps/libfreetype_sys-41348487f23312f6.rlib" "/home/goku/Programs/provok/target/release/deps/libserde-bed8adcfc49372ae.rlib" "/home/goku/Programs/provok/target/release/deps/libpalette-7bd53581ee1b150b.rlib" "/home/goku/Programs/provok/target/release/deps/libphf-7a6288ad1db4b8ce.rlib" "/home/goku/Programs/provok/target/release/deps/libphf_shared-9f4ea193894f7c58.rlib" "/home/goku/Programs/provok/target/release/deps/libsiphasher-fc9b34c771a5f939.rlib" "/home/goku/Programs/provok/target/release/deps/libapprox-6f21b4d27179d7d2.rlib" "/home/goku/Programs/provok/target/release/deps/libnum_traits-76497a4d2bc29446.rlib" "/home/goku/Programs/provok/target/release/deps/libclap-75ffc4e4161bdcd8.rlib" "/home/goku/Programs/provok/target/release/deps/libvec_map-7710e0aa1820f58b.rlib" "/home/goku/Programs/provok/target/release/deps/libtextwrap-af767440c987ca23.rlib" "/home/goku/Programs/provok/target/release/deps/libunicode_width-b8b37d5da2aa8f4a.rlib" "/home/goku/Programs/provok/target/release/deps/libstrsim-be518b8b7cca0422.rlib" "/home/goku/Programs/provok/target/release/deps/libatty-1dd903dbf50fd55b.rlib" "/home/goku/Programs/provok/target/release/deps/libansi_term-8403b5b7bcdb97e5.rlib" "/home/goku/Programs/provok/target/release/deps/libfailure-32ef14bc03e4ef86.rlib" "/home/goku/Programs/provok/target/release/deps/libglium-2d3d1b2ac08f3e63.rlib" "/home/goku/Programs/provok/target/release/deps/libbacktrace-8e20e6498ee14172.rlib" "/home/goku/Programs/provok/target/release/deps/libminiz_oxide-ae5f950f1808e1a2.rlib" "/home/goku/Programs/provok/target/release/deps/libadler-dd8d1d7a27bd42ae.rlib" "/home/goku/Programs/provok/target/release/deps/libobject-e8abed7a446e8066.rlib" "/home/goku/Programs/provok/target/release/deps/libaddr2line-5f7f466dee2da14b.rlib" "/home/goku/Programs/provok/target/release/deps/libgimli-d0db3d8fb158fc5a.rlib" "/home/goku/Programs/provok/target/release/deps/librustc_demangle-52c7d6c4fc90a912.rlib" "/home/goku/Programs/provok/target/release/deps/libmemoffset-011b24de92813b8a.rlib" "/home/goku/Programs/provok/target/release/deps/libtakeable_option-efa82f1f6dab3546.rlib" "/home/goku/Programs/provok/target/release/deps/libglutin-65ae796790eb6cae.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_egl-c092b41a3ede93a1.rlib" "/home/goku/Programs/provok/target/release/deps/libosmesa_sys-6d901980f1072195.rlib" "/home/goku/Programs/provok/target/release/deps/libshared_library-590e45c745d28542.rlib" "/home/goku/Programs/provok/target/release/deps/libwinit-266ca184e95815cd.rlib" "/home/goku/Programs/provok/target/release/deps/libmio_extras-8cdf33527bfaa748.rlib" "/home/goku/Programs/provok/target/release/deps/libmio-cae513901481b818.rlib" "/home/goku/Programs/provok/target/release/deps/libslab-7c378fecdd145a1f.rlib" "/home/goku/Programs/provok/target/release/deps/libiovec-00087cb6ac5f0e3d.rlib" "/home/goku/Programs/provok/target/release/deps/libnet2-3d6abda150f36f93.rlib" "/home/goku/Programs/provok/target/release/deps/liblazycell-9b9b292d449abec0.rlib" "/home/goku/Programs/provok/target/release/deps/libpercent_encoding-b156c77573f89cf5.rlib" "/home/goku/Programs/provok/target/release/deps/libsmithay_client_toolkit-d4c320ba081ebdac.rlib" "/home/goku/Programs/provok/target/release/deps/libandrew-9c6671f94655664f.rlib" "/home/goku/Programs/provok/target/release/deps/libxml-95ef26f620db547d.rlib" "/home/goku/Programs/provok/target/release/deps/libxdg-b8ff5ad2fb8fc313.rlib" "/home/goku/Programs/provok/target/release/deps/libwalkdir-41b4430d5b9d242b.rlib" "/home/goku/Programs/provok/target/release/deps/libsame_file-a07a72097e6c1124.rlib" "/home/goku/Programs/provok/target/release/deps/librusttype-0230aaf735eec52c.rlib" "/home/goku/Programs/provok/target/release/deps/libab_glyph_rasterizer-a8becb297cb6329f.rlib" "/home/goku/Programs/provok/target/release/deps/libowned_ttf_parser-d957499d1b39e9c4.rlib" "/home/goku/Programs/provok/target/release/deps/libttf_parser-7d160fd5742aeb24.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_cursor-c32f6838d060d276.rlib" "/home/goku/Programs/provok/target/release/deps/libxcursor-c7d2da2812b00dc9.rlib" "/home/goku/Programs/provok/target/release/deps/libnom-af011b6e6e7c2793.rlib" "/home/goku/Programs/provok/target/release/deps/libmemchr-6604bfb2160b8b24.rlib" "/home/goku/Programs/provok/target/release/deps/libmemmap2-5ac4d864528d130f.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_protocols-959e3f5ab5259d19.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_client-9ba37e5cf9d3e7ff.rlib" "/home/goku/Programs/provok/target/release/deps/libscoped_tls-325e20ef67f3a77e.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_commons-105d3605d2fc62b4.rlib" "/home/goku/Programs/provok/target/release/deps/libonce_cell-df7961e3e4cf3887.rlib" "/home/goku/Programs/provok/target/release/deps/libnix-9e8e2d5311dcca9a.rlib" "/home/goku/Programs/provok/target/release/deps/libwayland_sys-640c8c19939b7f9b.rlib" "/home/goku/Programs/provok/target/release/deps/libdlib-9b247eaa33d057f3.rlib" "/home/goku/Programs/provok/target/release/deps/liblibloading-6ce83f6c29d11a52.rlib" "/home/goku/Programs/provok/target/release/deps/libcalloop-ed4da5e032615079.rlib" "/home/goku/Programs/provok/target/release/deps/libnix-a852735c3093b7f6.rlib" "/home/goku/Programs/provok/target/release/deps/libcfg_if-6f3ad86205136786.rlib" "/home/goku/Programs/provok/target/release/deps/libdlib-45f2876b0eb63b19.rlib" "/home/goku/Programs/provok/target/release/deps/liblibloading-bd8d267b700561d4.rlib" "/home/goku/Programs/provok/target/release/deps/libraw_window_handle-996ead8d3f4d1122.rlib" "/home/goku/Programs/provok/target/release/deps/libparking_lot-ec8a45e1e6793e72.rlib" "/home/goku/Programs/provok/target/release/deps/libparking_lot_core-098d2eccfd774e43.rlib" "/home/goku/Programs/provok/target/release/deps/libsmallvec-dac38cb5d4c05e30.rlib" "/home/goku/Programs/provok/target/release/deps/liblock_api-15c92925ce66fe3f.rlib" "/home/goku/Programs/provok/target/release/deps/libscopeguard-e3010b47504e0224.rlib" "/home/goku/Programs/provok/target/release/deps/libinstant-41dd51f7c4e1661f.rlib" "/home/goku/Programs/provok/target/release/deps/libbitflags-5624065210ca120e.rlib" "/home/goku/Programs/provok/target/release/deps/libglutin_glx_sys-57c76da4fcfce488.rlib" "/home/goku/Programs/provok/target/release/deps/libx11_dl-4a4f5f4464d89ce7.rlib" "/home/goku/Programs/provok/target/release/deps/libmaybe_uninit-1700b8055919331a.rlib" "/home/goku/Programs/provok/target/release/deps/liblibc-393f1cefa144c9c3.rlib" "/home/goku/Programs/provok/target/release/deps/libglutin_egl_sys-6905be5ca2ebaf69.rlib" "/home/goku/Programs/provok/target/release/deps/liblog-26151b12ef260e13.rlib" "/home/goku/Programs/provok/target/release/deps/libcfg_if-0b1d0733c6ac953a.rlib" "/home/goku/Programs/provok/target/release/deps/libfnv-c8b023d9950bf602.rlib" "/home/goku/Programs/provok/target/release/deps/liblazy_static-1b6ec6226bff81a2.rlib" "-Wl,--start-group" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-b1047a2788193be4.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e8e399e2092f3b2a.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c6b02b522c91c060.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-eaad965909c4200f.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-dca728ac8ed54d87.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-4b4efaa8c4601753.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-d36e07ed2cc56ee4.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-3855d04b1bb40ceb.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-58a065cdff5508a2.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-82aeeedcc8d1450a.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5c4d6c9d7595f844.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-2642d2bccc00517a.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-760e48b3f782e7f5.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-d4ef8bf89076ed01.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-36070e2029bb21ea.rlib" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-3aaf8f932781f33e.rlib" "-Wl,--end-group" "/home/goku/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-e2523c360f03ba10.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lfreetype" "-ldl" "-ldl" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = **note: /usr/bin/ld: /home/goku/Programs/provok/target/release/deps/provok-5f4099590c69632c.provok.3i622bfx-cgu.15.rcgu.o: in function `provok::font::FontConfiguration::get_font':
          provok.3i622bfx-cgu.15:(.text._ZN6provok4font17FontConfiguration8get_font17hc9f8f19eba00801bE+0x7e7): undefined reference to `hb_ft_font_create_referenced'
          /usr/bin/ld: provok.3i622bfx-cgu.15:(.text._ZN6provok4font17FontConfiguration8get_font17hc9f8f19eba00801bE+0x7f5): undefined reference to `hb_ft_font_set_load_flags'**
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `provok`

To learn more, run the command again with --verbose.
make: *** [Makefile:2: build] Error 101

**Comment by o2sh** [comment]
Thanks for reporting the issue @mdatz, do you have `libharfbuzz-dev` installed on your machine ?
if not do a `sudo apt install  libharfbuzz-dev`and try again.

**Comment by o2sh** [comment]
Thanks for reporting the issue @mdatz, do you have libharfbuzz-dev installed on your machine ?
if not do a sudo apt install libharfbuzz-devand try again.

**Comment by mdatz** [comment]
That was it! Installed it and ran 'make clean & make uninstall' before trying the install again, works perfect now! Thanks for the help!!
